export const GRAMMAR_SEED = {
  topics: [
    { slug: 'present-simple',     name: 'Present Simple',           category: 'tenses' },
    { slug: 'present-continuous', name: 'Present Continuous',       category: 'tenses' },
    { slug: 'present-perfect',    name: 'Present Perfect',          category: 'tenses' },
    { slug: 'past-simple',        name: 'Past Simple',              category: 'tenses' },
    { slug: 'past-continuous',    name: 'Past Continuous & Past Perfect', category: 'tenses' },
    { slug: 'future-tenses',      name: 'Future Tenses',            category: 'tenses' },
    { slug: 'articles',           name: 'Articles',                 category: 'articles' },
    { slug: 'prepositions',       name: 'Prepositions',             category: 'prepositions' },
    { slug: 'sva',                name: 'Subject–Verb Agreement',   category: 'nouns' },
    { slug: 'conditionals',       name: 'Conditionals',             category: 'conditionals' },
    { slug: 'modals',             name: 'Modals',                   category: 'modals' },
    { slug: 'voice',              name: 'Voice (Active & Passive)', category: 'voice' },
    { slug: 'narration',          name: 'Narration (Direct & Indirect)', category: 'narration' },
    { slug: 'nouns-pronouns',     name: 'Nouns & Pronouns',         category: 'nouns' },
    { slug: 'adjectives-adverbs', name: 'Adjectives & Adverbs',     category: 'adjectives' },
    { slug: 'clauses',            name: 'Clauses & Conjunctions',   category: 'clauses' },
    { slug: 'punctuation',        name: 'Punctuation & Common Confusions', category: 'punctuation' },
  ],
  questions: [
    { topicSlug: 'present-simple',     prompt: 'She ___ to school every day.', options: ['go','goes','going','gone'], correctAnswer: 'goes', explain: 'He/She/It takes verb + -s.', banglaExplain: 'he/she/it এর সাথে verb-এ -s/-es যোগ হয়।' },
    { topicSlug: 'present-simple',     prompt: 'Water ___ at 100 degrees Celsius.', options: ['boil','boils','boiling','boiled'], correctAnswer: 'boils', explain: 'General truths use present simple.', banglaExplain: 'সাধারণ সত্য বোঝাতে present simple হয়।' },
    { topicSlug: 'present-continuous', prompt: 'Look! The baby ___ .', options: ['cries','cried','is crying','has cried'], correctAnswer: 'is crying', explain: 'Action happening now: am/is/are + -ing.', banglaExplain: 'এই মুহূর্তে চলমান কাজ: am/is/are + -ing।' },
    { topicSlug: 'present-perfect',    prompt: 'I ___ my homework already.', options: ['finish','finishes','have finished','finished'], correctAnswer: 'have finished', explain: 'I + have + past participle.', banglaExplain: 'I + have + past participle।' },
    { topicSlug: 'past-simple',        prompt: 'I ___ to Dhaka last week.', options: ['go','goes','went','going'], correctAnswer: 'went', explain: 'Past simple of "go".', banglaExplain: '"go" এর past form "went"।' },
    { topicSlug: 'past-continuous',    prompt: 'I ___ cooking when she called.', options: ['am','is','was','were'], correctAnswer: 'was', explain: 'I/He/She/It + was + -ing.', banglaExplain: 'I/he/she/it + was + -ing।' },
    { topicSlug: 'future-tenses',      prompt: 'I ___ you tomorrow.', options: ['call','calls','will call','called'], correctAnswer: 'will call', explain: 'Future simple: will + base.', banglaExplain: 'Future simple: will + base।' },
    { topicSlug: 'articles',           prompt: 'She is ___ honest student.', options: ['a','an','the','—'], correctAnswer: 'an', explain: 'Vowel sound → "an".', banglaExplain: 'Vowel sound → "an"।' },
    { topicSlug: 'prepositions',       prompt: 'I will meet you ___ Friday.', options: ['in','on','at','by'], correctAnswer: 'on', explain: 'Days → "on".', banglaExplain: 'দিনের আগে "on"।' },
    { topicSlug: 'sva',                prompt: 'Neither of the boys ___ ready.', options: ['is','are','were','have'], correctAnswer: 'is', explain: '"Neither of" → singular verb.', banglaExplain: '"Neither of" → singular verb।' },
    { topicSlug: 'conditionals',       prompt: 'If it rains, I ___ stay home.', options: ['will','would','had','am'], correctAnswer: 'will', explain: 'First conditional: If + present, will.', banglaExplain: 'First conditional: If + present, will।' },
    { topicSlug: 'modals',             prompt: 'You ___ see a doctor if the pain continues.', options: ['should','could','would','used to'], correctAnswer: 'should', explain: 'Advice → "should".', banglaExplain: 'পরামর্শ → "should"।' },
    { topicSlug: 'voice',              prompt: 'Passive of: "Rina writes a letter."', options: ['A letter is written by Rina.','A letter was written by Rina.','A letter has written by Rina.','A letter is writing by Rina.'], correctAnswer: 'A letter is written by Rina.', explain: 'Present simple passive: is/am/are + past participle.', banglaExplain: 'Present simple passive: is/am/are + past participle।' },
    { topicSlug: 'narration',          prompt: 'Indirect: He said, "I am tired."', options: ['He said that he was tired.','He said that I am tired.','He said that he is tired.','He says he was tired.'], correctAnswer: 'He said that he was tired.', explain: 'Present → past in indirect speech.', banglaExplain: 'Indirect speech এ present → past।' },
    { topicSlug: 'nouns-pronouns',     prompt: 'The news ___ good.', options: ['is','are','were','have'], correctAnswer: 'is', explain: '"News" is singular.', banglaExplain: '"News" singular।' },
    { topicSlug: 'adjectives-adverbs', prompt: 'This is ___ than that.', options: ['better','good','more better','best'], correctAnswer: 'better', explain: 'Comparative of "good".', banglaExplain: '"good" এর comparative "better"।' },
    { topicSlug: 'clauses',            prompt: 'I stayed home ___ it was raining.', options: ['because','although','but','so'], correctAnswer: 'because', explain: 'Cause → "because".', banglaExplain: 'কারণ → "because"।' },
    { topicSlug: 'punctuation',        prompt: 'Which is correct?', options: ['I bought apples, bananas, and oranges.','I bought apples bananas and oranges.','I bought apples, bananas and oranges.','I bought, apples, bananas, and oranges.'], correctAnswer: 'I bought apples, bananas, and oranges.', explain: 'Commas separate list items.', banglaExplain: 'তালিকার আইটেম আলাদা করতে কমা।' },
  ],
};
